environment:
  node_js_version: "4.1.1"

install:
  - ps: install-product node $env:node_js_version
  - npm install
  - npm install -g gulp
  - gulp init

build: off

test_script:
  - node --version
  - npm --version
  - gulp
